name: ci
on: pull_request
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
        working-directory: test
      - run: npx tsc
        working-directory: test
      - run: npx ava outer/*
        working-directory: test
